manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmkfirmware-kurtis
      url-base: https://github.com/kurtis-lew
  projects:
    - name: zmk
      remote: zmkfirmware-kurtis
      revision: update_behaviors
      import: app/west.yml
  self:
    path: config
